name: CI
on:
  pull_request:
  push:
    branches:
      - develop
      - release/*
    tags:
      - v**
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.11'
          # - 'lts' # long term support
          - '1'   # stable
          # - 'pre' # pre-release
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      
      - name: Cache Artifacts
        uses: julia-actions/cache@v3

      - name: Julia Build Pkg
        uses: julia-actions/julia-buildpkg@latest

      - name: Run tests
        env:
          IIF_TEST: true
        uses: julia-actions/julia-runtest@latest      
      - name: Process Coverage
        uses: julia-actions/julia-processcoverage@v1
        
      - name: Code Coverage
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup julia
        uses: julia-actions/setup-julia@v3
        with:
          version: '1.12'
          arch: x64

      - name: Build Docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: |
          julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
          julia --project=docs/ docs/make.jl
        
